const CourseData = [
      /*
    { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
    { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
    */
    {id: 1, courseNum:'COMP1000', CourseName:'Key Concepts in Computer Science', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Curtis Bright', Prereq:'None'},
    {id: 2, courseNum:'COMP1047', CourseName:'Computer Concepts for End-Users', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'David Mayo', Prereq:'None'},
    {id: 3, courseNum:'COMP1400', CourseName:'Intro to Programming and Algorithms I', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Dima Alhadidi', Prereq:'None'},
    {id: 4, courseNum:'COMP1410', CourseName:'Intro to Programming and Algorithms II', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Sherif Saad Ahmed', Prereq:'COMP-1000(Or MATH-1720) and COMP-1400'},
    {id: 5, courseNum:'COMP2057', CourseName:'Intro to the Internet', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'David Mayo', Prereq:'COMP-1047 or COMP-2067 or COMP-1400'},
    {id: 6, courseNum:'COMP2067', CourseName:'Programming for Beginners', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Arunita Jaekel', Prereq:'None'},
    {id: 7, courseNum:'COMP2077', CourseName:'Problem Solving and Information on the Internet', Fall:'Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Ziad Kobti', Prereq:'COMP-1047 and COMP-2057'},
    {id: 8, courseNum:'COMP2097', CourseName:'Social Media and Mobile Technology for End Users', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Pooya Moradian Zadeh', Prereq:'None'},
    {id: 9, courseNum:'COMP2120', CourseName:'Object Oriented Programming Using Java', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Saeed Samet', Prereq:'COMP-1410'},
    {id: 10, courseNum:'COMP2140', CourseName:'Computer Languages, Grammars, and Translators', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Jianguo Lu', Prereq:'COMP-1000 and COMP-2120'},
    {id: 11, courseNum:'COMP2310', CourseName:'Theoretical Foundations of Computer Science', Fall:'Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Ahmad Binizaz', Prereq:'COMP-1000 and MATH-1020'},
    {id: 12, courseNum:'COMP2540', CourseName:'Data Structures and Algorithms', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Scott Goodwin', Prereq:'COMP-1000 and COMP-1410'},
    {id: 13, courseNum:'COMP2560', CourseName:'System Programming', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Dan Wu', Prereq:'COMP-1410'},
    {id: 14, courseNum:'COMP2650', CourseName:'Computer Architecture I', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Hossein Fani', Prereq:'COMP-1400'},
    {id: 15, courseNum:'COMP2660', CourseName:'Computer Architecture II', Fall:'Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Alioune Ngom', Prereq:'COMP2650'},
    {id: 16, courseNum:'COMP2707', CourseName:'Advanced Website Design', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Saja AI Mamoori', Prereq:'COMP-2057'},
    {id: 17, courseNum:'COMP2800', CourseName:'Software Development', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Jessica Chen', Prereq:'COMP-2120'},
    {id: 18, courseNum:'COMP3057', CourseName:'Cyber-Ethics', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Ziad Kobti', Prereq:'COMP-1047 and COMP-2057'},
    {id: 19, courseNum:'COMP3077', CourseName:'Web-based Data Management', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Mahreen Nasir Butt', Prereq:'COMP-2707'},
    {id: 20, courseNum:'COMP3110', CourseName:'Introduction to Software Engineering', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'NA', Prereq:'COMP-2120,COMP-2540'},
    {id: 21, courseNum:'COMP3150', CourseName:'Database Management Systems', Fall:'Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Imran Ahmad', Prereq:'COMP-2540 and COMP-2560 or COMP-2650'},
    {id: 22, courseNum:'COMP3220', CourseName:'Obj Oriented Software Analysis and Design', Fall:'Offered', Summer:'Offered', Winter:'Offered', Instructor:'Dan Wu', Prereq:'COMP-2120 and COMP-2540'},
    {id: 23, courseNum:'COMP3300', CourseName:'Operating System Fundamentals', Fall:'Not Offered', Summer:'Offered', Winter:'Offered', Instructor:'Jessica Chen', Prereq:'COMP-2120, COMP-2540, COMP-2560, and COMP-2650 or COMP-2660'},
    {id: 24, courseNum:'COMP3340', CourseName:'WWW Information System Development', Fall:'Not Offered', Summer:'Offered', Winter:'Offered', Instructor:'Paul Preney', Prereq:'COMP-2120 and COMP-2540'},
    {id: 25, courseNum:'COMP3400', CourseName:'Advanced Object Oriented System Design Using C++', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Paul Preney', Prereq:'COMP-2120 and COMP-2560'},
    {id: 26, courseNum:'COMP3500', CourseName:'Introduction to Multimedia Systems', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'NA', Prereq:'COMP-2540 and COMP-2650'},
    {id: 27, courseNum:'COMP3520', CourseName:'Introduction to Computer Graphics', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'NA', Prereq:'COMP-2540 and MATH-1250'},
    {id: 28, courseNum:'COMP3540', CourseName:'Theory of Computation', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'NA', Prereq:'COMP-2140, COMP-2310, COMP-2540'},
    {id: 29, courseNum:'COMP3670', CourseName:'Computer Networks', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'NA', Prereq:'COMP-2120, COMP-2560, COMP-2540, COMP-2650'},
    {id: 30, courseNum:'COMP3680', CourseName:'Network Practicum', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'NA', Prereq:'COMP-3300,COMP-3670'},
    {id: 31, courseNum:'COMP3710', CourseName:'Artificial Intelligence Concepts', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Robin Gras', Prereq:'COMP-2540 and (STAT-2910 or STAT-2920)'},
    {id: 32, courseNum:'COMP3770', CourseName:'Game Design, Development, and Tools', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'Scott Goodwin', Prereq:'COMP-2540,COMP-2120'},
    {id: 33, courseNum:'COMP4110', CourseName:'Software Verification and Testing', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Majid Afshar Noghondari', Prereq:'COMP-3110,COMP-3300'},
    {id: 34, courseNum:'COMP4150', CourseName:'Advanced and Practical Database Systems', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'James Chevalier', Prereq:'COMP-3150,COMP-3300'},
    {id: 35, courseNum:'COMP4200', CourseName:'Mobile Application Development', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Shano Shuvo', Prereq:'COMP-3150,COMP-3220'},
    {id: 36, courseNum:'COMP4220', CourseName:'Agile Software Development', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'Xiaobu Yuan', Prereq:'COMP-3220'},
    {id: 37, courseNum:'COMP4250', CourseName:'Big Data Analytics and Database Design', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Saeed Samet', Prereq:'COMP-3150'},
    {id: 38, courseNum:'COMP4400', CourseName:'Principles of Programming Languages', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'Jessica Chen', Prereq:'COMP-2140,COMP-2310,COMP-2540'},
    {id: 39, courseNum:'COMP4540', CourseName:'Design and Analysis of Algorithms', Fall:'Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Peter Tsin', Prereq:'COMP-3540,COMP-2310,COMP-2540'},
    {id: 40, courseNum:'COMP4670', CourseName:'Network Security', Fall:'Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'NA', Prereq:'COMP-3670'},
    {id: 41, courseNum:'COMP4680', CourseName:'Advanced Networking', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Sherif Saad Ahmed', Prereq:'COMP-3670,COMP3680'},
    {id: 42, courseNum:'COMP4730', CourseName:'Machine Learning', Fall:'Not Offered', Summer:'Not Offered', Winter:'Not Offered', Instructor:'NA', Prereq:'COMP-3710'},
    {id: 43, courseNum:'COMP4740', CourseName:'Advanced Topics in AI II', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Robin Gras', Prereq:'COMP-3710'},
    {id: 44, courseNum:'COMP4770', CourseName:'Artifical Intelligence for Games', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Scott Goodwin', Prereq:'COMP-3770'},
    {id: 45, courseNum:'COMP4800', CourseName:'Selected Topics in Software Engineering', Fall:'Not Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Ikjot Saini', Prereq:'COMP-3110.COMP-3220,COMP3300'},
    {id: 46, courseNum:'COMP4960', CourseName:'Research Project', Fall:'Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Ziad Kobti', Prereq:'NA'},
    {id: 47, courseNum:'COMP4990', CourseName:'Project Management: Techniques and Tools', Fall:'Offered', Summer:'Not Offered', Winter:'Offered', Instructor:'Arunita Jaekel', Prereq:'NA'},

  ];

  export default CourseData;